version: "3"

services:
  flarum:
    image: mondedie/flarum:stable
    container_name: flarum
    env_file:
      - ./flarum.env
    volumes:
      - ./assets:/flarum/app/public/assets
      - ./extensions:/flarum/app/extensions
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - mariadb
    labels:
      - traefik.http.routers.gitlab-server.rule=Host(`gaming.doze.tech`)
      - traefik.http.routers.gitlab-server.tls=true
      - traefik.http.routers.gitlab-server.tls.certresolver=myresolver
      - traefik.http.services.gitlab-server.loadbalancer.server.port=80

  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - ./mysql:/var/lib/mysql